# Note: WIP

steps:
  
  # Decrypt secrets
  - name: 'gcr.io/cloud-builders/gcloud'   
    entrypoint: '/bin/sh'
    args:
    - -c
    - 'bin/kms decrypt test'

  # Unit test core function
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article Core && bin/test Article Core'

  # Unit test fetch function
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article Fetch && bin/test Article Fetch'

  # Deploy core main function
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article Core && bin/deploy function Article Core test'

  # Deploy core handle_fetched function
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article Core && bin/deploy function Article Core test --entry-point handle_fetched --subscribe Fetch'

  # Deploy fetch main function 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article Fetch && bin/deploy function Article Fetch test --subscribe Core'

  # Deploy default GAE service 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/build Article UI && bin/deploy app Article UI test --publish Core' 
  
  # Run system tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/test-api'

