
steps:
  
  # Decrypt secrets
  - name: 'gcr.io/cloud-builders/gcloud'   
    entrypoint: '/bin/sh'
    args:
    - -c
    - 'bin/kms decrypt ${_ENV} --project ${PROJECT_ID}'

  # Unit test write function
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/test functions write ${_ENV}'

  # Unit test fetch function
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/test functions fetch ${_ENV}'

  # Deploy write function
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/deploy functions write ${_ENV} --project ${PROJECT_ID}'

  # Deploy fetch function publishing to write (pubsub topic)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/deploy functions fetch ${_ENV} --publish-topic write --project ${PROJECT_ID}'

  # Deploy default GAE service 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/deploy services default ${_ENV} --project ${PROJECT_ID}
  
  # Run system tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: 
    - -c
    - 'bin/test-api ${PROJECT_ID} ${_ENV}'

substitutions:
  _ENV: test

